[package]
name = "vpadauk-plotter-cli"
version = "0.1.0"
authors = ["Vladislav Nikonov <pacmancoder@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vpadauk-plotter = { path = "../vpadauk-plotter" }